version: "3.5"

services:

  memcached:
    image: memcached:alpine
    container_name: memcached
    environment:
      - "TZ=${TZ}"
    restart: always

  db:
    image: mysql:8.0.17
    container_name: jagger_db
    command:
       - "--character-set-server=utf8mb4"
       - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  smtp_relay:
    image: juanluisbaptiste/postfix
    container_name: smtp_relay
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "SERVER_HOSTNAME=helpdesk.singaren.net.sg"
      - "SMTP_SERVER=${SMTP_SERVER}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
    restart: always

  jagger:
    image: jagger:v1.8.0
    container_name: jagger
    depends_on:
      - db
      - memcached
    ports:
      - 8081:80/tcp
    env_file:
      - ./.env
    restart: always

